### PR TITLE
typo in conf.py

### PR DESCRIPTION
**Pull request by hmenager**

### CODE REVIEW

**Comment by matuskalas** [comment]
_Not the most important stuff of all, but:_

Do we want all contributors as co-authors in the documentation, or separate between authors and contributors? (Both fine by me, but in the case of the latter, it would be nice to mention the contributors who gave advice, too)

**Comment by LucieLamothe** [comment]
Who more would we add? Maybe Johan but I feel like everyone is mentioned.

**Comment by LucieLamothe** [comment]
Also, are we naming is caseologue, Caseologuec Caséologue, caséologue? I think I like Caseologue best. What do you think @hmenager @matuskalas ?

**Comment by matuskalas** [comment]
> Also, are we naming is caseologue, Caseologuec Caséologue, caséologue? I think I like Caseologue best. What do you think @hmenager @matuskalas ?

I like Caséologue as the human name, and `caseologue` in the code / command line

**Review by matuskalas — APPROVED** [review]

**Pull request merged**
