### PR TITLE
Moved the test duplicate in concept from curation to error

### PR DESCRIPTION
**Pull request by maanst**

### CODE REVIEW

**Review by matuskalas — APPROVED** [review]
Awesome, thank you! 🙌🏽

**Comment by matuskalas** [comment]
I'm somewhat confused now: Why did this PR not launch the _test caseologue_ and _caseologue error essential_ CI workflows?
I thought we fixed that, but doesn't look like. Do you know what this is, @maanst ?

**Comment by maanst** [comment]
> I'm somewhat confused now: Why did this PR not launch the _test caseologue_ and _caseologue error essential_ CI workflows? I thought we fixed that, but doesn't look like. Do you know why this is, @maanst ?

I don't know...

**Comment by matuskalas** [comment]
Yes, for some weird reason they were both stuck in the test. Re-run now, with success, and merged both #13 and #14

**Pull request merged**
